### ISSUE TITLE
1.0.29-beta invalid zip

### ISSUE THREAD

**Issue by theScrabi** [micro-a5k/microg-unofficial-installer#13]
twrp tells me the latest release has an invalid zip format.

**Comment by ale5000-git** [comment]
I have tried both v1.0.29-beta and the latest master on TWRP 3.1.0-0 with `Zip signature verification` enabled and it pass.

Maybe you got corrupted files, try to delete it and download it again.

**Comment by ale5000-git** [comment]
For the future I intend to add hash check everywhere, currently is only for downloaded files on build and internal files on install (beside the normal zip signing).

**Comment by theScrabi** [comment]
Hm I tested in on two devices, my Mac, and my linux computer. Also I used the zip form github and xda. Maybe there is something wrong with my twrp installation.
However did you pack the files using Mac?

**Comment by ale5000-git** [comment]
I use Windows.
The zip from GitHub is only sources (not flashable), you have to extract it and use `build.sh` to create the flashable zip.

**Comment by theScrabi** [comment]
> The zip from GitHub is only sources (not flashable), you have to extract it and use build.sh to create the flashable zip

That could have been the reason xD

**Comment by ale5000-git** [comment]
I have to put the instructions in the readme but I have too much things in my ToDO queue :)

**Comment by theScrabi** [comment]
> I have too much things in my ToDO queue :)

Relatable :D

**Comment by ale5000-git** [comment]
@theScrabi
Hi,
now the OSS only version is automatically released on GitHub, so it easier to get it.
