### ISSUE TITLE
Bysybox does not include zip. In build.sh, zip is used, resulting in unsuccessful operation. Line 107: not found.ERROR: Failed compressing

### ISSUE THREAD

**Issue by 873578156** [micro-a5k/microg-unofficial-installer#2]
Bysybox does not include zip. In build.sh, zip is used, resulting in unsuccessful operation.
Line 107: not found.ERROR: Failed compressing

**Comment by ale5000-git** [comment]
Doh, I have installed zip on my system some times ago so I haven't noticed this problem.

I will fix it this evening.

**Comment by ale5000-git** [comment]
Sorry to be late, it should be fixed now,
