### ISSUE TITLE
Include Needle

### ISSUE THREAD

**Issue by geromueller** [micro-a5k/microg-unofficial-installer#3]
Since many devices have SignatureSpoofing disabled (e.g. MIUI) it would be awesome if you could include the fix as well: https://github.com/moosd/Needle

**Comment by ale5000-git** [comment]
@geromueller: It is true that microG need signature spoofing but installing microG and patch the ROM for signature spoofing are two different thing that in my opinion should not be merged together.

PS: I have a tool called Tingle to enable signature spoofing and in the future it will be able to operate also as flashable ZIP.

**Comment by geromueller** [comment]
Hi,

yes, flashable ZIP would be great! Thanks.
