### ISSUE TITLE
Not install google playstore

### ISSUE THREAD

**Issue by theScrabi** [micro-a5k/microg-unofficial-installer#4]
Is there a way to not install google playstore?

**Comment by ale5000-git** [comment]
@theScrabi: Yes, if you enable live setup (by pressing the + volume button during installation) and selecting FakeStore.

**Comment by theScrabi** [comment]
Either that or set the 'MARKET' varable in the [setup.conf](https://github.com/micro-a5k/microg-unofficial-installer/blob/master/sources/settings.conf) to FakeStore.

Sorry I was writing issues faster than I could fix it.

**Comment by ale5000-git** [comment]
In the future there will be also external configuration.

**Comment by theScrabi** [comment]
Noice

**Comment by ale5000-git** [comment]
You can also use OSS variant that don't include the PlayStore at all.
