### ISSUE TITLE
LegacyNetworkLocation causing bootloop 4.2.2

### ISSUE THREAD

**Issue by falcon4fun** [micro-a5k/microg-unofficial-installer#6]
So, LegacyNetworkLocation crashing system_server (: 
I don't know what should I include ( :

**Comment by ale5000-git** [comment]
1) Could you please post the result of this command?
> ls /system/app

2) Post a copy of /system/framework/framework-res.apk

3) Post a logcat of the bootloop

**Comment by ale5000-git** [comment]
@falcon4fun

Hi,
I need these things:

1. Could you please post the result of this command?
> ls /system/app

2. Post a copy of /system/framework/framework-res.apk

3. Post the log of the installer
(do not copy it manually, but after flashing the zip use the option of the recovery to copy log to SD and then post the file)

4. Post a logcat of the bootloop

**Comment by ale5000-git** [comment]
@falcon4fun
Could you please try [this version](https://www.androidfilehost.com/?fid=889964283620773383) to see if there are any improvements?

**Comment by falcon4fun** [comment]
@ale5000-git sry, i'm so fast in answering :D
Checked your archive. No bootloop now. But I've changed Gmscore from 81 to 105 (or 107). Don't know why but 81 don't work after installing zip (: 

Plus unifiedNlp writes that no location get and MicroG checking writes that UnifiedNlp is not registered but location, backends, geocoder is working.
Don't know why, but I've patched framework-res before and it works on your latest 107 version :D

**Comment by ale5000-git** [comment]
@falcon4fun
It install version 81 on old Android versions since the latest version has a bug that doesn't allow to add a Google account.

Could you please test [microG unofficial installer 1.0.26 alpha](https://androidfilehost.com/?w=files&flid=141201) to see if all problems are fixed?
