### ISSUE TITLE
put releases on github

### ISSUE THREAD

**Issue by theScrabi** [micro-a5k/microg-unofficial-installer#7]
Hello @ale5000-git could you put your updates on your [releases](https://github.com/micro-a5k/microg-unofficial-installer/releases) page on github. This way one can subscibe it with an rss reader, and get notified whenever you create a new version. :D 

Awesome work by the way, I love this installer :)

**Comment by ale5000-git** [comment]
I haven't yet added releases here since I still feel it to be incomplete.
I have intention to do it but before doing it I want to add external settings support and a FAQ page.

They will probably be in the next release but currently I'm busy with other things so I don't know exactly when I will have time.
But I think it will be in a few days.

**Comment by theScrabi** [comment]
All right thanks :D

**Comment by ale5000-git** [comment]
I didn't have time to finish the mentioned features but I have decided to release it anyway as beta.

**Comment by theScrabi** [comment]
> Removed F-Droid Privileged Extension, it will be in a separate package in the future

So i have to run a separate installer in order to get privileged extension running again?

**Comment by ale5000-git** [comment]
Installing only the F-Droid Privileged Extension without F-Droid could cause problems if the version of F-Droid (manually installed from the user) isn't updated and it could also cause the inability to install anything in some cases.

I will create another flashable zip with it together with other App Stores that can be choosed.

**Comment by ildar** [comment]
> Installing only the F-Droid Privileged Extension without F-Droid could
> cause problems if the version of F-Droid (manually installed from the user)
> isn't updated and it could also cause the inability to install anything in
> some cases.
>
This is very surprising.
Can you give details or did you open the issue on gitlab?

**Comment by ale5000-git** [comment]
I remember that I had to disable F-Droid Privileged Extension in F-Droid options to get app installed.
It happened to me some times ago with an old version of F-Droid together with the latest version of F-Droid Privileged Extension, I don't remember exactly now.

**Comment by ildar** [comment]
well, that's a pity.
Yet I don't see how removing the `F-Droid Privileged Extension` would
positively change anything. Just my IMHO, of course.

**Comment by theScrabi** [comment]
@ale5000-git maybe you can make it optional as well.

**Comment by ale5000-git** [comment]
@theScrabi @ildar

As said I have the intention of creating a separate flashable zip for app stores.
And keeping F-Droid Privileged Extension here and F-Droid in the other separate flashable zip would be senseless and also would be a nightmare to avoid conflicts.

But do not worry I have some ideas to create a way in the future to flash multiple zips at once (everyone with its one settings); so at the end would be the same.
Unfortunately I cannot do everything now for the lack of time.

**Comment by ildar** [comment]
> Unfortunately I cannot do everything now for the lack of time.

This is very important. We have a lot in our offline life. 🙂

> And keeping F-Droid Privileged Extension here and F-Droid in the other
> separate flashable zip would be senseless and also would be a nightmare to
> avoid conflicts.
>
This part I completely disagree in. Let me explain.
FDPE is made small and quiet on purpose. Anyone is safe to install it in
any Android regardless. Even if a user doesn't use F-Droid, it's ok. I
personally recommend it to anyone.
F-Droid main app is optional. Most ROMs don't need to carry it. Yet it is
easy to install and will work great without any special treatment: no need
to put it on /system etc.

**Comment by ale5000-git** [comment]
@ildar
Apps in /system/app doesn't get privileged permissions, but it is still comfortable to place them in a place that survive a device wipe.
I don't see any downside in putting it inside /system/app beside low free space; but in the future I will also add a check for it.

Also as already said there will be options so you can also install only F-Droid Privileged Extension from the new flashable zip if you want.

So with options in a separate file plus auto flash of multiple zips (both future things), then will be the same as before.
